#!/usr/bin/env Rscript

#' Imports assets from the official Krona repo
download_assets <- function(version, outdir) {
  url = if (grepl('.', version, fixed = TRUE)) {
    sprintf('https://github.com/marbl/Krona/archive/refs/tags/v%s.zip',
            version)
  } else {
    # commit hash or 'master'
    sprintf('https://github.com/marbl/Krona/archive/%s.zip',
            version)
  }
  download.file(url, 'Krona.zip')
  unzip('Krona.zip', exdir = 'Krona')
  file.remove('Krona.zip')
  img.assets <- c('favicon.ico', 'hidden.png', 'loading.gif', 'logo-med.png')
  files <- c('src/krona-2.0.js',
             paste0('img/', img.assets),
             paste0('img/', gsub('\\.[^.]+', '.uri', img.assets)))
  ktdir <- file.path('Krona',
                     list.files('Krona', pattern = 'Krona-*')[1],
                     'KronaTools')
  for (f in files) {
    d <- file.path(outdir, dirname(f))
    dir.create(d, FALSE, TRUE)
    file.rename(file.path(ktdir, f), file.path(outdir, f))
  }
  file.rename(file.path(ktdir, 'LICENSE.txt'), 'KRONA_LICENSE')
  unlink('Krona', recursive = TRUE)
}

get_copyright_header <- function(krona_js) {
  js <- readLines(krona_js)
  first_blank_i <- which(nchar(trimws(js)) == 0)[1]
  stopifnot(!is.na(first_blank_i), first_blank_i > 1)
  paste(js[1:(first_blank_i - 1)], collapse = '\n')
}

minify_krona = function(base_dir, js_path, repo_base) {
  js_file <- file.path(base_dir, js_path)
  js_min_path <- gsub('\\.js$', '.min.js', js_path)
  outfile <- file.path(base_dir, js_min_path)
  version <- system2(c('uglifyjs', '--version'), stdout = TRUE)

  # run uglifyjs
  # (needs to be installed and in PATH)
  # TODO: more aggressive toplevel mangling could be applied to get it down to <50kb, but it's quite complicated
  cmd <- c('uglifyjs', js_file, '--mangle', '--mangle-props')
  jsmin <- system2(cmd, stdout = TRUE)

  # Create minified JS with informative header
  cat(sprintf(
    paste(
      '// NOTE: https://github.com/marbl/Krona/tree/master/KronaTools/%s, minified with %s\n',
      '// See %s/%s\n',
      '// Original copyright notice below:\n'
    ),
    js_path,
    version,
    repo_base,
    js_min_path
  ),
  file = outfile)
  js <- readLines(js_file)
  first_blank_i <- which(nchar(trimws(js)) == 0)[1]
  stopifnot(!is.na(first_blank_i), first_blank_i > 1)
  header <- get_copyright_header(js_file)
  cat(header, sep = '\n', file = outfile, append = TRUE)
  cat(jsmin, file = outfile, append = TRUE)

  # return version
  list(
    program_path = Sys.which('uglifyjs'),
    version = version,
    command = paste(cmd, collapse = ' ')
  )
}

info = 'This folder contains an unmodified copy of files downloaded
from https://github.com/marbl/Krona

Directories:
- KronaTools/src
- KronaTools/img

These assets are included in the HTML charts generated by the
`generate_krona_html_internal()` function.

Snapshot version: %s

In addition, a minified JS file is included to allow creating slightly smaller
HTML files with less lines (`minify = TRUE` argument):

KronaTools/src/krona-2.0.min.js

This is always used when embedding charts to improve performance and avoid
some problem during PDF generation.

Minified with https://github.com/mishoo/UglifyJS:
Program: %s
Version: %s
Command: %s
'

if (sys.nframe() == 0) {
  # current version is '2.8.1', but it misses the 'showMagnitude' option,
  # so we use the latest commit
  outdir <- 'inst/KronaTools'
  version <- 'd1479b3'
  repo_base <- 'https://github.com/markschl/RKrona'
  download_assets(version, outdir)
  repo_base <- paste0('https://github.com/markschl/RKrona/', outdir)
  js_file <- 'src/krona-2.0.js'
  u <- minify_krona(outdir, js_file, repo_base = repo_base)
  cat(sprintf(info, version, u$program_path, u$version, u$command),
      file = file.path(outdir, 'README.txt'))
}
